apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: IfNotPresent
      restartPolicy: Always

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-affinity
  labels:
    app: nginx-affinity
spec:
  containers:
    - name: nginx-affinity
      image: nginx
      imagePullPolicy: IfNotPresent
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: cpu
                operator: In
                values:
                  - fast
                  - superFast
      preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
              - key: cpu
                operator: In
                values:
                  - fast
          weight: 10
  restartPolicy: Always


---

apiVersion: v1
kind: Pod
metadata:
  name: initContainer
  labels:
    app: initContainer
spec:
  containers:
    - name: initContainer
      image: busybox
      imagePullPolicy: IfNotPresent
  initContainers:
    - name: initContainer-1
      image: busybox
      command: ["/bin/sh","-c","echo init-1 && sleep 5"]
    - name: initContainer-2
      image: busybox
      command: ["/bin/sh","-c","echo init-2 && sleep 5"]
  nodeSelector:
    cpu: fast
  nodeName: k8s-node
  restartPolicy: Always


---
apiVersion: v1
kind: Pod
metadata:
  name: Title
  labels:
    app: Title
spec:
  containers:
    - name: Title
      image: nginx
      imagePullPolicy: IfNotPresent
      livenessProbe:
        exec:
          command:
            - ls
            - /var/run/nginx.pid
        initialDelaySeconds: 5
      resources:
        requests:
          memory: "100Mi"
          cpu: "0.5"
        limits:
          memory: "200Mi"
          cpu: "1"

  restartPolicy: Always



---

apiVersion: v1
kind: Pod
metadata:
  name: Title
  labels:
    app: Title
spec:
  containers:
    - name: Title
      image: nginx
      imagePullPolicy: IfNotPresent

  restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: Title
spec:
  selector:
    app: Title
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
