name: Unit

on: [ pull_request,push ]

env:
  GITHUB_ACTIONS: true

jobs:
  test:
    name: "Tests (${{ matrix.os }})"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        go: [ '1.x' ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with: { fetch-depth: 1 }
      - uses: actions/setup-go@v2
        with: { go-version: "${{ matrix.go }}" }
      - run: go version
      - run: go test -v -race=true ./...

  bench:
    name: Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: { fetch-depth: 1 }
      - uses: actions/setup-go@v2
        with: { go-version: '1.x' }
      - run: go version
      - run: go test -bench=. ./...
